// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/logstream/messages.proto

package logstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Level int32

const (
	Level_LEVEL_INFO  Level = 0
	Level_LEVEL_WARN  Level = 1
	Level_LEVEL_ERROR Level = 2
)

// Enum value maps for Level.
var (
	Level_name = map[int32]string{
		0: "LEVEL_INFO",
		1: "LEVEL_WARN",
		2: "LEVEL_ERROR",
	}
	Level_value = map[string]int32{
		"LEVEL_INFO":  0,
		"LEVEL_WARN":  1,
		"LEVEL_ERROR": 2,
	}
)

func (x Level) Enum() *Level {
	p := new(Level)
	*p = x
	return p
}

func (x Level) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Level) Descriptor() protoreflect.EnumDescriptor {
	return file_api_logstream_messages_proto_enumTypes[0].Descriptor()
}

func (Level) Type() protoreflect.EnumType {
	return &file_api_logstream_messages_proto_enumTypes[0]
}

func (x Level) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Level.Descriptor instead.
func (Level) EnumDescriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{0}
}

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // log id
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`                     // log source
	Level         Level                  `protobuf:"varint,3,opt,name=level,proto3,enum=logstream.Level" json:"level,omitempty"` // log level (info, warn, error)
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_api_logstream_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Log) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Log) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_INFO
}

func (x *Log) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Log) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SaveLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *Log                   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLogRequest) Reset() {
	*x = SaveLogRequest{}
	mi := &file_api_logstream_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLogRequest) ProtoMessage() {}

func (x *SaveLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLogRequest.ProtoReflect.Descriptor instead.
func (*SaveLogRequest) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{1}
}

func (x *SaveLogRequest) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type SaveLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLogResponse) Reset() {
	*x = SaveLogResponse{}
	mi := &file_api_logstream_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLogResponse) ProtoMessage() {}

func (x *SaveLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLogResponse.ProtoReflect.Descriptor instead.
func (*SaveLogResponse) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SaveLogResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SaveLogsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *Log                   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLogsStreamRequest) Reset() {
	*x = SaveLogsStreamRequest{}
	mi := &file_api_logstream_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLogsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLogsStreamRequest) ProtoMessage() {}

func (x *SaveLogsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLogsStreamRequest.ProtoReflect.Descriptor instead.
func (*SaveLogsStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{3}
}

func (x *SaveLogsStreamRequest) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

type SaveLogsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveLogsStreamResponse) Reset() {
	*x = SaveLogsStreamResponse{}
	mi := &file_api_logstream_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveLogsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveLogsStreamResponse) ProtoMessage() {}

func (x *SaveLogsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveLogsStreamResponse.ProtoReflect.Descriptor instead.
func (*SaveLogsStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{4}
}

func (x *SaveLogsStreamResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         Level                  `protobuf:"varint,1,opt,name=level,proto3,enum=logstream.Level" json:"level,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsRequest) Reset() {
	*x = ListLogsRequest{}
	mi := &file_api_logstream_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsRequest) ProtoMessage() {}

func (x *ListLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsRequest.ProtoReflect.Descriptor instead.
func (*ListLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ListLogsRequest) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_INFO
}

func (x *ListLogsRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListLogsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ListLogsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ListLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*Log                 `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsResponse) Reset() {
	*x = ListLogsResponse{}
	mi := &file_api_logstream_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsResponse) ProtoMessage() {}

func (x *ListLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsResponse.ProtoReflect.Descriptor instead.
func (*ListLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ListLogsResponse) GetLogs() []*Log {
	if x != nil {
		return x.Logs
	}
	return nil
}

type ListLogsStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         Level                  `protobuf:"varint,1,opt,name=level,proto3,enum=logstream.Level" json:"level,omitempty"`
	Keyword       string                 `protobuf:"bytes,2,opt,name=keyword,proto3" json:"keyword,omitempty"`
	StartTime     int64                  `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsStreamRequest) Reset() {
	*x = ListLogsStreamRequest{}
	mi := &file_api_logstream_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsStreamRequest) ProtoMessage() {}

func (x *ListLogsStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsStreamRequest.ProtoReflect.Descriptor instead.
func (*ListLogsStreamRequest) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{7}
}

func (x *ListLogsStreamRequest) GetLevel() Level {
	if x != nil {
		return x.Level
	}
	return Level_LEVEL_INFO
}

func (x *ListLogsStreamRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListLogsStreamRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ListLogsStreamRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type ListLogsStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Log           *Log                   `protobuf:"bytes,1,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLogsStreamResponse) Reset() {
	*x = ListLogsStreamResponse{}
	mi := &file_api_logstream_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLogsStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLogsStreamResponse) ProtoMessage() {}

func (x *ListLogsStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_logstream_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLogsStreamResponse.ProtoReflect.Descriptor instead.
func (*ListLogsStreamResponse) Descriptor() ([]byte, []int) {
	return file_api_logstream_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ListLogsStreamResponse) GetLog() *Log {
	if x != nil {
		return x.Log
	}
	return nil
}

var File_api_logstream_messages_proto protoreflect.FileDescriptor

const file_api_logstream_messages_proto_rawDesc = "" +
	"\n" +
	"\x1capi/logstream/messages.proto\x12\tlogstream\"\x8d\x01\n" +
	"\x03Log\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12&\n" +
	"\x05level\x18\x03 \x01(\x0e2\x10.logstream.LevelR\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"2\n" +
	"\x0eSaveLogRequest\x12 \n" +
	"\x03log\x18\x01 \x01(\v2\x0e.logstream.LogR\x03log\"!\n" +
	"\x0fSaveLogResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"9\n" +
	"\x15SaveLogsStreamRequest\x12 \n" +
	"\x03log\x18\x01 \x01(\v2\x0e.logstream.LogR\x03log\"(\n" +
	"\x16SaveLogsStreamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8d\x01\n" +
	"\x0fListLogsRequest\x12&\n" +
	"\x05level\x18\x01 \x01(\x0e2\x10.logstream.LevelR\x05level\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\"6\n" +
	"\x10ListLogsResponse\x12\"\n" +
	"\x04logs\x18\x01 \x03(\v2\x0e.logstream.LogR\x04logs\"\x93\x01\n" +
	"\x15ListLogsStreamRequest\x12&\n" +
	"\x05level\x18\x01 \x01(\x0e2\x10.logstream.LevelR\x05level\x12\x18\n" +
	"\akeyword\x18\x02 \x01(\tR\akeyword\x12\x1d\n" +
	"\n" +
	"start_time\x18\x03 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x04 \x01(\x03R\aendTime\":\n" +
	"\x16ListLogsStreamResponse\x12 \n" +
	"\x03log\x18\x01 \x01(\v2\x0e.logstream.LogR\x03log*8\n" +
	"\x05Level\x12\x0e\n" +
	"\n" +
	"LEVEL_INFO\x10\x00\x12\x0e\n" +
	"\n" +
	"LEVEL_WARN\x10\x01\x12\x0f\n" +
	"\vLEVEL_ERROR\x10\x02B'Z%logstream/pkg/api/logstream;logstreamb\x06proto3"

var (
	file_api_logstream_messages_proto_rawDescOnce sync.Once
	file_api_logstream_messages_proto_rawDescData []byte
)

func file_api_logstream_messages_proto_rawDescGZIP() []byte {
	file_api_logstream_messages_proto_rawDescOnce.Do(func() {
		file_api_logstream_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_logstream_messages_proto_rawDesc), len(file_api_logstream_messages_proto_rawDesc)))
	})
	return file_api_logstream_messages_proto_rawDescData
}

var file_api_logstream_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_logstream_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_logstream_messages_proto_goTypes = []any{
	(Level)(0),                     // 0: logstream.Level
	(*Log)(nil),                    // 1: logstream.Log
	(*SaveLogRequest)(nil),         // 2: logstream.SaveLogRequest
	(*SaveLogResponse)(nil),        // 3: logstream.SaveLogResponse
	(*SaveLogsStreamRequest)(nil),  // 4: logstream.SaveLogsStreamRequest
	(*SaveLogsStreamResponse)(nil), // 5: logstream.SaveLogsStreamResponse
	(*ListLogsRequest)(nil),        // 6: logstream.ListLogsRequest
	(*ListLogsResponse)(nil),       // 7: logstream.ListLogsResponse
	(*ListLogsStreamRequest)(nil),  // 8: logstream.ListLogsStreamRequest
	(*ListLogsStreamResponse)(nil), // 9: logstream.ListLogsStreamResponse
}
var file_api_logstream_messages_proto_depIdxs = []int32{
	0, // 0: logstream.Log.level:type_name -> logstream.Level
	1, // 1: logstream.SaveLogRequest.log:type_name -> logstream.Log
	1, // 2: logstream.SaveLogsStreamRequest.log:type_name -> logstream.Log
	0, // 3: logstream.ListLogsRequest.level:type_name -> logstream.Level
	1, // 4: logstream.ListLogsResponse.logs:type_name -> logstream.Log
	0, // 5: logstream.ListLogsStreamRequest.level:type_name -> logstream.Level
	1, // 6: logstream.ListLogsStreamResponse.log:type_name -> logstream.Log
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_api_logstream_messages_proto_init() }
func file_api_logstream_messages_proto_init() {
	if File_api_logstream_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_logstream_messages_proto_rawDesc), len(file_api_logstream_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_logstream_messages_proto_goTypes,
		DependencyIndexes: file_api_logstream_messages_proto_depIdxs,
		EnumInfos:         file_api_logstream_messages_proto_enumTypes,
		MessageInfos:      file_api_logstream_messages_proto_msgTypes,
	}.Build()
	File_api_logstream_messages_proto = out.File
	file_api_logstream_messages_proto_goTypes = nil
	file_api_logstream_messages_proto_depIdxs = nil
}
