// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/logstream/service.proto

package logstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_logstream_service_proto protoreflect.FileDescriptor

const file_api_logstream_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/logstream/service.proto\x12\tlogstream\x1a\x1capi/logstream/messages.proto2\xc8\x02\n" +
	"\vLogsService\x12@\n" +
	"\aSaveLog\x12\x19.logstream.SaveLogRequest\x1a\x1a.logstream.SaveLogResponse\x12Y\n" +
	"\x0eSaveLogsStream\x12 .logstream.SaveLogsStreamRequest\x1a!.logstream.SaveLogsStreamResponse(\x010\x01\x12C\n" +
	"\bListLogs\x12\x1a.logstream.ListLogsRequest\x1a\x1b.logstream.ListLogsResponse\x12W\n" +
	"\x0eListLogsStream\x12 .logstream.ListLogsStreamRequest\x1a!.logstream.ListLogsStreamResponse0\x01B'Z%logstream/pkg/api/logstream;logstreamb\x06proto3"

var file_api_logstream_service_proto_goTypes = []any{
	(*SaveLogRequest)(nil),         // 0: logstream.SaveLogRequest
	(*SaveLogsStreamRequest)(nil),  // 1: logstream.SaveLogsStreamRequest
	(*ListLogsRequest)(nil),        // 2: logstream.ListLogsRequest
	(*ListLogsStreamRequest)(nil),  // 3: logstream.ListLogsStreamRequest
	(*SaveLogResponse)(nil),        // 4: logstream.SaveLogResponse
	(*SaveLogsStreamResponse)(nil), // 5: logstream.SaveLogsStreamResponse
	(*ListLogsResponse)(nil),       // 6: logstream.ListLogsResponse
	(*ListLogsStreamResponse)(nil), // 7: logstream.ListLogsStreamResponse
}
var file_api_logstream_service_proto_depIdxs = []int32{
	0, // 0: logstream.LogsService.SaveLog:input_type -> logstream.SaveLogRequest
	1, // 1: logstream.LogsService.SaveLogsStream:input_type -> logstream.SaveLogsStreamRequest
	2, // 2: logstream.LogsService.ListLogs:input_type -> logstream.ListLogsRequest
	3, // 3: logstream.LogsService.ListLogsStream:input_type -> logstream.ListLogsStreamRequest
	4, // 4: logstream.LogsService.SaveLog:output_type -> logstream.SaveLogResponse
	5, // 5: logstream.LogsService.SaveLogsStream:output_type -> logstream.SaveLogsStreamResponse
	6, // 6: logstream.LogsService.ListLogs:output_type -> logstream.ListLogsResponse
	7, // 7: logstream.LogsService.ListLogsStream:output_type -> logstream.ListLogsStreamResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_logstream_service_proto_init() }
func file_api_logstream_service_proto_init() {
	if File_api_logstream_service_proto != nil {
		return
	}
	file_api_logstream_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_logstream_service_proto_rawDesc), len(file_api_logstream_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_logstream_service_proto_goTypes,
		DependencyIndexes: file_api_logstream_service_proto_depIdxs,
	}.Build()
	File_api_logstream_service_proto = out.File
	file_api_logstream_service_proto_goTypes = nil
	file_api_logstream_service_proto_depIdxs = nil
}
